const data = [{
  servingSize: '500 mL',
  calories: 340,
  totalFat: {
    qty: 17,
    perc: 10,
    saturatedFat: { qty: 1.5, perc: 3 },
    transFat: { qty: 6, perc: null },
  },
  cholesterol: { qty: 13, perc: 2 },
  sodium: { qty: 300, perc: 5 },
  totalCarbohydrate: {
    qty: 44,
    perc: 18,
    dietaryFiber: { qty: 12, perc: 2 },
    sugars: { qty: 18, perc: 14 },
  },
  protein: { qty: 10, perc: null },
  vitaminA: { perc: 4 },
  vitaminB: { perc: 14 },
  vitaminC: { perc: 5 },
  vitaminD: { perc: 12 },
  vitaminE: { perc: 5 },
  calcium: { perc: 6 },
  iron: { perc: 2 },
  potassium: { perc: 7 },
},
{
  servingSize: '120g',
  calories: 278,
  totalFat: {
    qty: 18,
    perc: 3,
    saturatedFat: { qty: 4, perc: 1 },
    transFat: { qty: 6, perc: null },
  },
  cholesterol: { qty: 34, perc: 7 },
  sodium: { qty: 5, perc: 1 },
  totalCarbohydrate: {
    qty: 12,
    perc: 1,
    dietaryFiber: { qty: 35, perc: 3 },
    sugars: { qty: 12, perc: 1 },
  },
  protein: { qty: 3, perc: null },
  vitaminA: { perc: 1 },
  vitaminB: { perc: 3 },
  vitaminC: { perc: 10 },
  vitaminD: { perc: 2 },
  vitaminE: { perc: 5 },
  calcium: { perc: 8 },
  iron: { perc: 1 },
  potassium: { perc: 9 },
},
{
  servingSize: '500 mL',
  calories: 225,
  totalFat: {
    qty: 1.6,
    perc: 1,
    saturatedFat: { qty: 0.5, perc: 3 },
    transFat: { qty: 0, perc: null },
  },
  cholesterol: { qty: 13, perc: 2 },
  sodium: { qty: 92, perc: 9 },
  totalCarbohydrate: {
    qty: 48,
    perc: 2.8,
    dietaryFiber: { qty: 10, perc: 1 },
    sugars: { qty: 25, perc: 3 },
  },
  protein: { qty: 8, perc: null },
  vitaminA: { perc: 1 },
  vitaminB: { perc: 9 },
  vitaminC: { perc: 3 },
  vitaminD: { perc: 18 },
  vitaminE: { perc: 4 },
  calcium: { perc: 12 },
  iron: { perc: 4 },
  potassium: { perc: 9 },
},
];
export default data;
